--- #YAML:1.0
name:                BigIP-ParseConfig
version:             1.1.1
abstract:            F5/BigIP configuration parser
license:             perl
generated_by         ExtUtils::MakeMaker version 6.32
distribution_type:   module
author:
    - Scott Schneider <sschneid@gmail.com>

